### ISSUE TITLE
NullPointerException in the call manager

### ISSUE THREAD

**Issue by jmauffret** [android-rcs/rcsjta#120]
NullPointerException in the call manager :

07-07 14:15:46.212: E/AndroidRuntime(1480): FATAL EXCEPTION: Timer-46
07-07 14:15:46.212: E/AndroidRuntime(1480): Process: com.gsma.rcs, PID: 1480
07-07 14:15:46.212: E/AndroidRuntime(1480): java.lang.NullPointerException
07-07 14:15:46.212: E/AndroidRuntime(1480):    at com.gsma.rcs.core.ims.service.capability.CapabilityService.requestContactCapabilities(CapabilityService.java:171)
07-07 14:15:46.212: E/AndroidRuntime(1480):    at com.gsma.rcs.core.ims.network.gsm.CallManager.requestCapabilities(CallManager.java:324)
07-07 14:15:46.212: E/AndroidRuntime(1480):    at com.gsma.rcs.core.ims.network.gsm.CallManager.access$8(CallManager.java:322)
07-07 14:15:46.212: E/AndroidRuntime(1480):    at com.gsma.rcs.core.ims.network.gsm.CallManager$1$1.run(CallManager.java:230)
07-07 14:15:46.212: E/AndroidRuntime(1480):    at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by jmauffret** [comment]
For an incoming call, if for any reason the remote contact is not well identified during the RINGING state, then there is a NullPointerException when requesting the capabilities in the stae CONNECTED
