### ISSUE TITLE
Missing Lollipop support: bindService() is not always called with an explicit intent

### ISSUE THREAD

**Issue by uekemp** [android-rcs/rcsjta#127]
Since API level 21 bindService() must always be called with an explicit intent, which is not always the case. This raises an exception on Lollipop devices when trying to connect to a service. For example:

`Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.gsma.services.rcs.capability.ICapabilityService }
            at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1173)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1272)
            at android.app.ContextImpl.bindService(ContextImpl.java:1250)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:590)
            at com.gsma.services.rcs.capability.CapabilityService.connect(CapabilityService.java:83)`

For details on explicit intents see [Intent Types](http://developer.android.com/guide/components/intents-filters.html#Types).

**Comment by yplo6403** [comment]
Can you please attach the logcat file with the exception ?
The latest release to consider is the "integration" branch (and not the "master") in which Lollipop support has been taken into account.

**Comment by uekemp** [comment]
I confirm that this has been fixed in the integration branch, closing the issue.
