### ISSUE TITLE
NPE while receiving GC store and forward invitation

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#141]
__Initial conditions:__ 3 devices A, B and C. A and B are registered on line. C is in air plane mode.

__Action 1:__ A initiates a GC with B and C
__Action 2:__ C recovers the radio or WiFi access
__Expected result:__ The AS sends a store and forward GC invitation to C which rejoins the conversation.
__Result:__
<code>
09-22 15:45:56.222: V/[RCS][SipInterface](3505): <<< Receive SIP INVITE
09-22 15:45:56.222: V/[RCS][SipInterface](3505): Notify a SIP listener
09-22 15:45:56.222: V/[RCS][ImsServiceDispatcher](3505): Receive INVITE request
09-22 15:45:56.232: V/[RCS][SipInterface](3505): >>> Send SIP 100 response
09-22 15:45:56.242: V/[RCS][ImsServiceDispatcher](3505): Ad-hoc group chat session invitation
09-22 15:45:56.242: E/[RCS][ImsServiceDispatcher](3505): Failed to dispatch received SIP request! CallId=3104b31a95eb50fe5eeb76b856ec1beb@172.20.65.194
09-22 15:45:56.242: E/[RCS][ImsServiceDispatcher](3505): java.lang.NullPointerException
09-22 15:45:56.242: E/[RCS][ImsServiceDispatcher](3505):   at com.gsma.rcs.core.ims.service.im.InstantMessagingService.receiveAdhocGroupChatSession(InstantMessagingService.java:1042)
09-22 15:45:56.242: E/[RCS][ImsServiceDispatcher](3505):   at com.gsma.rcs.core.ims.service.ImsServiceDispatcher.dispatch(ImsServiceDispatcher.java:365)
09-22 15:45:56.242: E/[RCS][ImsServiceDispatcher](3505):   at com.gsma.rcs.core.ims.service.ImsServiceDispatcher.run(ImsServiceDispatcher.java:120)
</code>

In case of a GC S&F invitation, the remote contact is provided by the referredById field. If the invitation is due to a rejoin, the referredById field is not present.

**Comment by yplo6403** [comment]
Bug of the AS which should provide the remote contact in the ReferredBiId header field.
